const r=require('express').Router(),multer=require('multer'),path=require('path'),fs=require('fs'),{z}=require('zod');const {auth,allow}=require('../middleware/auth');const {User,Department,Team,Project,Task,Comment,Notification,Audit}=require('../models');const {ok,log,projectProgress,overdue}=require('../utils/core');
r.use(auth);const page=async(Model,q,req,pop='')=>{const p=Math.max(+req.query.page||1,1),limit=Math.min(+req.query.limit||20,100),[data,total]=await Promise.all([Model.find(q).populate(pop).sort('-createdAt').skip((p-1)*limit).limit(limit),Model.countDocuments(q)]);return {data,pagination:{page:p,limit,total,totalPages:Math.ceil(total/limit)}}};const projectPop='department manager team';const taskPop='project assignedTo createdBy department';
const canProject=(u,p)=>u.role==='ADMIN'||String(p.manager?._id||p.manager)===String(u._id)||(p.team?.members||[]).some(x=>String(x)===String(u._id));
// Dashboard is computed from persisted documents, scoped to the current role.
r.get('/dashboard',async(req,res,next)=>{try{const base=req.user.role==='EMPLOYEE'?{assignedTo:req.user._id}:req.user.role==='MANAGER'?{createdBy:req.user._id}:{};const [total,completed,overdueCount,dueToday,tasks,projects,employees,depts,teams]=await Promise.all([Task.countDocuments(base),Task.countDocuments({...base,status:'Completed'}),Task.countDocuments(overdue(base)),Task.countDocuments({...base,dueDate:{$gte:new Date(new Date().setHours(0,0,0,0)),$lt:new Date(new Date().setHours(24,0,0,0))},status:{$ne:'Completed'}}),Task.find(base).populate(taskPop).sort({dueDate:1}).limit(7),Project.find(req.user.role==='MANAGER'?{manager:req.user._id}:{}).populate(projectPop),User.countDocuments({active:true}),Department.countDocuments(),Team.countDocuments()]);const enriched=await Promise.all(projects.map(async p=>({...p.toObject(),progress:await projectProgress(p._id)})));ok(res,{stats:{total,completed,pending:total-completed,overdue:overdueCount,dueToday,projects:projects.length,employees,depts,teams,completion:total?Math.round(completed/total*100):0},focus:tasks,projects:enriched})}catch(e){next(e)}});
// users, departments and teams
r.get('/users',allow('ADMIN'),async(req,res,next)=>{try{const q=req.query.search?{$or:[{name:{$regex:req.query.search,$options:'i'}},{email:{$regex:req.query.search,$options:'i'}},{employeeId:{$regex:req.query.search,$options:'i'}}]}:{};const x=await page(User,q,req,'department team');ok(res,x.data,'Success',{pagination:x.pagination})}catch(e){next(e)}});
r.post('/users',allow('ADMIN'),async(req,res,next)=>{try{const v=z.object({name:z.string().min(2),email:z.string().email(),employeeId:z.string().min(2),password:z.string().min(8),role:z.enum(['ADMIN','MANAGER','EMPLOYEE']).default('EMPLOYEE')}).parse(req.body);const bcrypt=require('bcryptjs');const u=await User.create({...v,password:await bcrypt.hash(v.password,12),department:req.body.department,team:req.body.team});await log(req.user._id,'created','user',u._id);const data=u.toObject();delete data.password;ok(res,data,'Employee created successfully')}catch(e){next(e)}});
r.patch('/users/:id/status',allow('ADMIN'),async(req,res,next)=>{try{const u=await User.findByIdAndUpdate(req.params.id,{active:!!req.body.active},{new:true});ok(res,u,'Employee status updated')}catch(e){next(e)}});
r.get('/departments',async(req,res,next)=>{try{ok(res,await Department.find().sort('name'))}catch(e){next(e)}});r.post('/departments',allow('ADMIN'),async(req,res,next)=>{try{const d=await Department.create({name:req.body.name,description:req.body.description});ok(res,d,'Department created')}catch(e){next(e)}});
r.get('/teams',async(req,res,next)=>{try{const x=await page(Team,{},req,'department manager members');ok(res,x.data,'Success',{pagination:x.pagination})}catch(e){next(e)}});r.post('/teams',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const t=await Team.create(req.body);ok(res,t,'Team created')}catch(e){next(e)}});
// projects
r.get('/projects',async(req,res,next)=>{try{let q={};if(req.user.role==='MANAGER')q.manager=req.user._id;if(req.query.status)q.status=req.query.status;if(req.query.department)q.department=req.query.department;const x=await page(Project,q,req,projectPop);const data=await Promise.all(x.data.map(async p=>({...p.toObject(),progress:await projectProgress(p._id)})));ok(res,data,'Success',{pagination:x.pagination})}catch(e){next(e)}});
r.post('/projects',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const v=z.object({name:z.string().min(3),code:z.string().min(2),endDate:z.coerce.date(),startDate:z.coerce.date(),priority:z.enum(['Low','Medium','High','Critical']).optional()}).parse(req.body);if(v.endDate<v.startDate)return res.status(400).json({success:false,message:'End date cannot be earlier than start date'});const p=await Project.create({...req.body,createdBy:req.user._id,manager:req.user.role==='MANAGER'?req.user._id:req.body.manager});await log(req.user._id,'created','project',p._id);ok(res,p,'Project created successfully')}catch(e){next(e)}});
r.get('/projects/:id',async(req,res,next)=>{try{const p=await Project.findById(req.params.id).populate(projectPop);if(!p)return res.status(404).json({success:false,message:'Project not found'});const tasks=await Task.find({project:p._id}).populate(taskPop);ok(res,{...p.toObject(),progress:await projectProgress(p._id),tasks})}catch(e){next(e)}});
r.put('/projects/:id',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const p=await Project.findById(req.params.id).populate('team');if(!p||!canProject(req.user,p))return res.status(403).json({success:false,message:'You cannot edit this project'});Object.assign(p,req.body);await p.save();ok(res,p,'Project updated')}catch(e){next(e)}});
// tasks
r.get('/tasks',async(req,res,next)=>{try{let q={};if(req.user.role==='EMPLOYEE')q.assignedTo=req.user._id;if(req.query.project)q.project=req.query.project;if(req.query.status)q.status=req.query.status;if(req.query.priority)q.priority=req.query.priority;if(req.query.overdue==='true')q=overdue(q);const x=await page(Task,q,req,taskPop);ok(res,x.data,'Success',{pagination:x.pagination})}catch(e){next(e)}});
r.post('/tasks',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const v=z.object({title:z.string().min(3),project:z.string(),dueDate:z.coerce.date(),startDate:z.coerce.date().optional(),priority:z.enum(['Low','Medium','High','Critical']).optional()}).parse(req.body);if(v.startDate&&v.dueDate<v.startDate)return res.status(400).json({success:false,message:'Due date cannot be earlier than start date'});const t=await Task.create({...req.body,createdBy:req.user._id});if(t.assignedTo)await Notification.create({recipient:t.assignedTo,message:`You have been assigned “${t.title}”.`,link:`/tasks/${t._id}`});await log(req.user._id,'created','task',t._id);ok(res,t,'Task created successfully')}catch(e){next(e)}});
r.get('/tasks/:id',async(req,res,next)=>{try{const t=await Task.findById(req.params.id).populate(taskPop);if(!t)return res.status(404).json({success:false,message:'Task not found'});if(req.user.role==='EMPLOYEE'&&String(t.assignedTo?._id)!==String(req.user._id))return res.status(403).json({success:false,message:'Access denied'});const comments=await Comment.find({task:t._id}).populate('author','name avatar').sort('createdAt');ok(res,{...t.toObject(),comments})}catch(e){next(e)}});
r.put('/tasks/:id',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const t=await Task.findByIdAndUpdate(req.params.id,req.body,{new:true});ok(res,t,'Task updated')}catch(e){next(e)}});
r.patch('/tasks/:id/status',async(req,res,next)=>{try{const t=await Task.findById(req.params.id);if(!t)return res.status(404).json({success:false,message:'Task not found'});if(req.user.role==='EMPLOYEE'&&String(t.assignedTo)!==String(req.user._id))return res.status(403).json({success:false,message:'Only the assignee can update this task'});const from=t.status;t.status=req.body.status;await t.save();await log(req.user._id,`changed status from ${from} to ${t.status}`,'task',t._id);ok(res,t,'Task status updated')}catch(e){next(e)}});
r.patch('/tasks/:id/assign',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const t=await Task.findByIdAndUpdate(req.params.id,{assignedTo:req.body.assignedTo},{new:true});await Notification.create({recipient:req.body.assignedTo,message:`You have been assigned “${t.title}”.`,link:`/tasks/${t._id}`});ok(res,t,'Task reassigned')}catch(e){next(e)}});
r.delete('/tasks/:id',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{await Task.findByIdAndDelete(req.params.id);ok(res,null,'Task deleted')}catch(e){next(e)}});
// comments, files, reports and activity
r.get('/tasks/:id/comments',async(req,res,next)=>{try{ok(res,await Comment.find({task:req.params.id}).populate('author','name avatar').sort('createdAt'))}catch(e){next(e)}});r.post('/tasks/:id/comments',async(req,res,next)=>{try{const c=await Comment.create({task:req.params.id,author:req.user._id,body:req.body.body,parent:req.body.parent||null});const t=await Task.findById(req.params.id);if(t.assignedTo&&String(t.assignedTo)!==String(req.user._id))await Notification.create({recipient:t.assignedTo,message:`New comment on “${t.title}”.`,link:`/tasks/${t._id}`});ok(res,await c.populate('author','name avatar'),'Comment added')}catch(e){next(e)}});
const upload=multer({dest:process.env.UPLOAD_DIR||'uploads',limits:{fileSize:5*1024*1024},fileFilter:(q,f,cb)=>cb(null,['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/jpeg','image/png'].includes(f.mimetype))});r.post('/tasks/:id/attachments',upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({success:false,message:'Please upload a supported file up to 5MB'});const t=await Task.findById(req.params.id);t.attachments.push({name:path.basename(req.file.originalname),mime:req.file.mimetype,size:req.file.size,path:req.file.path,uploadedBy:req.user._id});await t.save();ok(res,t.attachments.at(-1),'File uploaded')}catch(e){next(e)}});
r.get('/notifications',async(req,res,next)=>{try{ok(res,await Notification.find({recipient:req.user._id}).sort('-createdAt').limit(30))}catch(e){next(e)}});r.patch('/notifications/:id/read',async(req,res,next)=>{try{ok(res,await Notification.findOneAndUpdate({_id:req.params.id,recipient:req.user._id},{read:true},{new:true}))}catch(e){next(e)}});r.get('/audit-logs',allow('ADMIN'),async(req,res,next)=>{try{const x=await page(Audit,{},req,'user');ok(res,x.data,'Success',{pagination:x.pagination})}catch(e){next(e)}});
r.get('/reports/tasks',allow('ADMIN','MANAGER'),async(req,res,next)=>{try{const all=await Task.find(req.query.project?{project:req.query.project}:{}).populate(taskPop);const rows=all.map(t=>({title:t.title,project:t.project?.name,assignee:t.assignedTo?.name,status:t.status,priority:t.priority,dueDate:t.dueDate,overdue:t.status!=='Completed'&&t.dueDate<new Date()}));if(req.query.format==='csv'){res.type('text/csv').attachment('workhub-task-report.csv').send(['Task,Project,Assignee,Status,Priority,Due Date,Overdue',...rows.map(x=>Object.values(x).map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n'));}else ok(res,rows,'Task report generated')}catch(e){next(e)}});module.exports=r;
